FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
COPY /scripts/installRuntimes.py /var/remote/installRuntimes.py
COPY /scripts/toinstall.txt /var/remote/toinstall.txt
COPY /scripts/startForDocker.sh /var/remote/startForDocker.sh

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install apt-transport-https -y 
RUN apt-get install ca-certificates  -y
RUN apt-get install curl -y
RUN apt-get install gnupg -y
RUN apt-get install lsb-release -y
RUN apt-get install python3 -y
RUN apt-get install git -y
  
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

RUN echo \
"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update
RUN apt-get install docker-ce -y
RUN apt-get install docker-ce-cli -y
RUN apt-get install containerd.io -y
RUN apt-get install nodejs -y
RUN apt-get install npm -y
RUN apt-get install iproute2 -y

RUN curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

RUN chmod +x /usr/local/bin/docker-compose

RUN service docker start

RUN ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

RUN git clone -b v3 https://github.com/engineer-man/piston /var/docker/piston

RUN npm install -g yarn 

RUN  yarn --cwd /var/docker/piston/cli

RUN chmod +x /var/remote/startForDocker.sh

ENTRYPOINT ["/bin/bash","-c","/var/remote/startForDocker.sh"]
