version: '3.3'
services:
  ubuntu:
    container_name: ubuntu_remote_compiler
    #image: ubuntu:20.04
    build: .
    privileged: true
    restart: always
    ports:
      - '9999:6969' 
      #This port is not beeing used!!!!
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    #  - "./scripts:/var/remote"
    #volumes:
    #  - "./scripts:/var/remote"
    #command: sh -c "tail -f /dev/null"
volumes:
  my-piston: