version: "3.9"
services:
  rest-api:
    image: rest-api
    container_name: rest-api
    build:
      context: RestWebservice-RemoteCompiling
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  code-analysis-api:
    image: code-analysis-api
    container_name: code-analysis-api
    build:
      context: .
      dockerfile: RestWebservice-StaticCodeAnalysis/Dockerfile
    ports:
      - "6001:80"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Sonarqube__ServerUrl=http://sonarqube:9000
      - Valgrind__Flags=--leak-check=full --show-leak-kinds=all --track-origins=yes
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    build: .
    ports:
      - "9001:9000"