version: "3.9"
services:
  rest-api:
    image: rest-api
    container_name: remotecompiler_rest-api
    build:
      context: RestWebservice-RemoteCompiling
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:Database=Server=db;Port=5432;Database=remote;User Id=remote_user;Password=remote_password;
  code-analysis-api:
    image: code-analysis-api
    container_name: remotecompiler_staticode
    build:
      context: .
      dockerfile: RestWebservice-StaticCodeAnalysis/Dockerfile
    ports:
      - "6001:80"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Sonarqube:ServerUrl=http://sonarqube:9000
      - Valgrind:Flags=--leak-check=full --show-leak-kinds=all --track-origins=yes
  db:
    image: postgres
    container_name: remotecompiler_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=remote_password
      - POSTGRES_USER=remote_user
      - POSTGRES_DB=remote
  sonarqube:
    image: sonarqube
    ports:
      - "9001:9000"